---
takel_bit_server_repo_dir: /bit

takel_bit_server_bit_user: bit
takel_bit_server_bit_uid: 2500
takel_bit_server_bit_group: bit
takel_bit_server_bit_gid: 2500
takel_bit_server_bit_shell: /bin/bash
takel_bit_server_bit_home: /home/bit

takel_bit_server_bit_config_dir: "{{ takel_bit_server_bit_home }}/Library/Caches/Bit/config"
takel_bit_server_bit_config_file: config.json
takel_bit_server_bit_config_path: "{{ takel_bit_server_bit_config_dir }}/{{ takel_bit_server_bit_config_file }}"

takel_bit_server_users:
  - myuser

takel_bit_server_sshpubkeys_custom:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEE3TDo5mJYPogviD2UmoKDOT6lnpK8xd35OopFo8hLQKdaqB4IXOxy+sINh9iElEOWq2nvpb4YQZTMT3t9y/PImE4JwixtvnASczHkZuj2pkx+mO1Q4XBVkOFFDzF5pwQ3GxJFNG8TSaKWgXL2IkeufJ6tgrfyCJR7lfwA0tTuIr4nIcTqa8LFxf3g98lgHoq3XYce6l87vDL+gz6S8glOysq1Phi0BjvnDx7Kfh8K6EVON5YKvAiw/BS4V/07CnTRlupA5ysVQpj1/bnR3DYwL7a2w2QDHuKyWKXcBZydBJjzvGWcx046nHgHvGYAvzrZyLO/6EyMSWWo4QJS6bFjqQ5E/9re+FVlvYnowCfpqO6/+B9BKC1stoQIXdvu8SWJpLwt71Kt+Bi8jrVLwpb+oZ7Y8TbAQcJ+gW/h4KkO9J3GkrsmudH5B33SuQZXc1dV5U0e3YaTu8NPRXdjEloclVNQGprhsR3KwRrKuWREguYioVOX9soV3I30HLfQn8= myuser@bitboard
