---
project: takelage-bit
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase
dockerhub_base_tag: debian-buster
dockerhub_prod_user: takelage
dockerhub_prod_repo: bitboard
local_user: packer_local
google_firewall_prod:
  - desc: ssh
    proto: tcp
    port: 222
version: 0.2.0
