---
# project settings
project: takelbit
version: 0.4.0
local_user: packer_local

# dockerhub settings for the base image
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase
dockerhub_base_tag: debian-buster

# dockerhub settings
dockerhub_prod_user: takelage
dockerhub_prod_repo: bitboard
ssh_port: 222

# google production settings
google_firewall_prod: []
