---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      rules:
        line-length: disable
platforms:
  - name: molecule-takel-users
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_users_users:
          - myuser
        takel_users_userdata:
          myuser:
            id: 1500
            full_name: My Testuser
            groups:
              - sudo
            ssh:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEE3TDo5mJYPogviD2UmoKDOT6lnpK8xd35OopFo8hLQKdaqB4IXOxy+sINh9iElEOWq2nvpb4YQZTMT3t9y/PImE4JwixtvnASczHkZuj2pkx+mO1Q4XBVkOFFDzF5pwQ3GxJFNG8TSaKWgXL2IkeufJ6tgrfyCJR7lfwA0tTuIr4nIcTqa8LFxf3g98lgHoq3XYce6l87vDL+gz6S8glOysq1Phi0BjvnDx7Kfh8K6EVON5YKvAiw/BS4V/07CnTRlupA5ysVQpj1/bnR3DYwL7a2w2QDHuKyWKXcBZydBJjzvGWcx046nHgHvGYAvzrZyLO/6EyMSWWo4QJS6bFjqQ5E/9re+FVlvYnowCfpqO6/+B9BKC1stoQIXdvu8SWJpLwt71Kt+Bi8jrVLwpb+oZ7Y8TbAQcJ+gW/h4KkO9J3GkrsmudH5B33SuQZXc1dV5U0e3YaTu8NPRXdjEloclVNQGprhsR3KwRrKuWREguYioVOX9soV3I30HLfQn8= myuser@bitboard
            # clear text password: myuserpassword
            password_hash: $$6$$qjgWdktPUZzfNWin$$3RoiFMGR9I2aA50wbLOvWMkt/VpFVMA34UFNPpj5f/zyaYsNRYU7fn31PBHRwKAVfRH/LEqKSAjcJ4j1toIam.
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../system/test_*.py
  options:
    # p: cacheprovider
    s: true
    v: true
  lint:
    name: flake8
scenario:
  name: default
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
