---
- name: (user) create bit group
  group:
    name: "{{ takel_bit_server_bit_group }}"
    gid: "{{ takel_bit_server_bit_gid }}"

- name: (user) create bit user
  user:
    name: "{{ takel_bit_server_bit_user }}"
    uid: "{{ takel_bit_server_bit_uid }}"
    group: "{{ takel_bit_server_bit_group }}"
    shell: "{{ takel_bit_server_bit_shell }}"
    home: "{{ takel_bit_server_bit_home }}"
    password_lock: true

- name: (user) create bit config dir
  file:
    path: "{{ takel_bit_server_bit_config_dir }}"
    owner: "{{ takel_bit_server_bit_user }}"
    group: "{{ takel_bit_server_bit_group }}"
    mode: 0755
    state: directory

- name: (user) create bit config json file
  template:
    src: config.json.j2
    dest: "{{ takel_bit_server_bit_config_path }}"
    owner: "{{ takel_bit_server_bit_user }}"
    group: "{{ takel_bit_server_bit_group }}"
    mode: 0644

- name: (user) add custom ssh keys to the authorized_keys file of the bit user
  authorized_key:
    key: "{{ item | default(omit) }}"
    user: "{{ takel_bit_server_bit_user }}"
  loop: "{{ takel_bit_server_sshpubkeys_custom }}"
