---
- name: (gcs) create directory for gcs credentials
  file:
    path: "{{ takel_gcsfuse_gcs_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory

- name: (gcs) copy gcs service account file
  copy:
    content: "{{ takel_gcsfuse_gcs_bucket_key }}"
    dest: "{{ takel_gcsfuse_gcs_dir }}/{{ takel_gcsfuse_gcs_file }}"
    owner: root
    group: root
    mode: 0600
  when: takel_gcsfuse_gcs_bucket_key is defined
