---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_gcsfuse
    - takel_gcsfuse_install

- name: (main) include gcs
  import_tasks: gcs.yml
  tags:
    - takel
    - takel_gcsfuse
    - takel_gcsfuse_gcs

- name: (main) include mount
  import_tasks: mount.yml
  tags:
    - takel
    - takel_gcsfuse
    - takel_gcsfuse_mount
