---
- name: (mount) create mount points
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ vikunja_gcsfuse_mounts }}"
  when: vikunja_gcsfuse_mounts | length > 0

- name: (mount) mount buckets
  mount:
    path: "{{ item.path }}"
    src:  "{{ item.bucket }}"
    fstype: gcsfuse
    opts: "rw,allow_other,uid={{ item.uid | default(1001) }},gid={{ item.gid | default(1001) }},key_file={{ vikunja_gcsfuse_gcs_path }}"
    state: present
  loop: "{{ vikunja_gcsfuse_mounts }}"
