---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takel-takelbit-test-image-${TAKELAGE_PROJECT_ENV:-prod}
    image: packer_local/mapapp:${TAKELAGE_PROJECT_ENV:-prod}
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - users
      - molecule
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    v: true
dependency:
  name: shell
  command: rake features:cucumber[@${TAKELAGE_PROJECT_ENV:-prod}]
scenario:
  dependency_sequence:
    - dependency
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    # - dependency
    - destroy
